apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-cli
  template:
    metadata:
      labels:
        app: news-cli
    spec:
      containers:
      - name: news-cli
        image: news-cli:latest
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: news
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: secret
        - name: REDIS_HOST
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
